local _, Addon = ...

local Keys = Addon.PreferenceKeys
local L = Addon.L

local APPEARANCE_PANEL = "appearance"
local BEHAVIOUR_PANEL = "behaviour"
local HEALTH_PANEL = "health"
local PLATES_PANEL = "plates"
local WINDOWS_PANEL = "windows"

--- Every preference the addon exposes, as data.
--- Adding an entry here is enough for it to be persisted and to show up in the
--- options panel; no adapter needs to change.
---@type Preference[]
local PreferenceCatalog = {
	{
		key = Keys.ENABLED,
		kind = "boolean",
		default = true,
		label = L.PREF_ENABLED,
		tooltip = L.PREF_ENABLED_TIP,
	},
	{
		key = Keys.SHOW_MINIMAP_BUTTON,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_MINIMAP_BUTTON,
		tooltip = L.PREF_SHOW_MINIMAP_BUTTON_TIP,
	},
	{
		key = Keys.ANNOUNCE_ON_LOAD,
		kind = "boolean",
		default = false,
		label = L.PREF_ANNOUNCE_ON_LOAD,
		tooltip = L.PREF_ANNOUNCE_ON_LOAD_TIP,
	},

	{
		key = Keys.VISIBILITY_MODE,
		panel = BEHAVIOUR_PANEL,
		kind = "string",
		default = Addon.VisibilityModes.COMBAT,
		label = L.PREF_VISIBILITY,
		tooltip = L.PREF_VISIBILITY_TIP,
		choices = Addon.VisibilityModes.Choices,
	},
	{
		key = Keys.HOLD_DURATION,
		panel = BEHAVIOUR_PANEL,
		kind = "number",
		default = 4,
		label = L.PREF_HOLD_DURATION,
		tooltip = L.PREF_HOLD_DURATION_TIP,
		minimum = 1,
		maximum = 15,
		step = 1,
	},
	{
		key = Keys.FLOATING_FALLBACK,
		panel = BEHAVIOUR_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_FLOATING_FALLBACK,
		tooltip = L.PREF_FLOATING_FALLBACK_TIP,
	},
	{
		key = Keys.SHOW_ON_FRIENDLY,
		panel = BEHAVIOUR_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_SHOW_ON_FRIENDLY,
		tooltip = L.PREF_SHOW_ON_FRIENDLY_TIP,
	},
	{
		key = Keys.TRACK_OTHER_UNITS,
		panel = BEHAVIOUR_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_TRACK_OTHER_UNITS,
		tooltip = L.PREF_TRACK_OTHER_UNITS_TIP,
	},

	{
		key = Keys.ICON_WIDTH,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = 24,
		label = L.PREF_ICON_WIDTH,
		tooltip = L.PREF_ICON_WIDTH_TIP,
		minimum = 16,
		maximum = 120,
		step = 2,
	},
	{
		key = Keys.ICON_HEIGHT,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = 24,
		label = L.PREF_ICON_HEIGHT,
		tooltip = L.PREF_ICON_HEIGHT_TIP,
		minimum = 16,
		maximum = 120,
		step = 2,
	},
	{
		key = Keys.ICON_ALPHA,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = 100,
		label = L.PREF_ICON_ALPHA,
		tooltip = L.PREF_ICON_ALPHA_TIP,
		minimum = 20,
		maximum = 100,
		step = 5,
	},
	{
		key = Keys.ANCHOR_POINT,
		panel = APPEARANCE_PANEL,
		kind = "string",
		default = "left",
		label = L.PREF_ANCHOR_POINT,
		tooltip = L.PREF_ANCHOR_POINT_TIP,
		choices = Addon.AnchorPoints.Choices,
	},
	{
		key = Keys.OFFSET_X,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = -7,
		label = L.PREF_OFFSET_X,
		tooltip = L.PREF_OFFSET_X_TIP,
		minimum = -200,
		maximum = 200,
		step = 1,
	},
	{
		key = Keys.OFFSET_Y,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = 0,
		label = L.PREF_OFFSET_Y,
		tooltip = L.PREF_OFFSET_Y_TIP,
		minimum = -200,
		maximum = 200,
		step = 1,
	},
	{
		key = Keys.SHOW_SWIPE,
		panel = APPEARANCE_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_SWIPE,
		tooltip = L.PREF_SHOW_SWIPE_TIP,
	},
	{
		key = Keys.SHOW_TIMER_TEXT,
		panel = APPEARANCE_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_TIMER_TEXT,
		tooltip = L.PREF_SHOW_TIMER_TEXT_TIP,
	},
	{
		key = Keys.BORDER_THICKNESS,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = 1,
		label = L.PREF_BORDER_THICKNESS,
		tooltip = L.PREF_BORDER_THICKNESS_TIP,
		minimum = 0,
		maximum = 6,
		step = 1,
	},
	{
		key = Keys.BORDER_COLOR,
		panel = APPEARANCE_PANEL,
		kind = "color",
		default = "0A0A0A",
		label = L.PREF_BORDER_COLOR,
		tooltip = L.PREF_BORDER_COLOR_TIP,
	},
	{
		key = Keys.FONT_NAME,
		panel = APPEARANCE_PANEL,
		kind = "string",
		default = "Inter",
		label = L.PREF_FONT,
		tooltip = L.PREF_FONT_TIP,
		-- Sem lista aqui: as fontes disponiveis so existem depois que todos os
		-- addons registraram as suas, entao a pagina resolve a lista ao abrir.
	},
	{
		key = Keys.FONT_SIZE,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = 14,
		label = L.PREF_FONT_SIZE,
		tooltip = L.PREF_FONT_SIZE_TIP,
		minimum = 8,
		maximum = 24,
		step = 1,
	},
	{
		key = Keys.FONT_FLAG,
		panel = APPEARANCE_PANEL,
		kind = "string",
		default = "OUTLINE",
		label = L.PREF_FONT_FLAG,
		tooltip = L.PREF_FONT_FLAG_TIP,
		choices = Addon.FontFlags.Choices,
	},

	{
		key = Keys.HEALTH_TEXT_ENABLED,
		panel = HEALTH_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_HEALTH_TEXT,
		tooltip = L.PREF_HEALTH_TEXT_TIP,
	},
	{
		key = Keys.HEALTH_TEXT_FORMAT,
		panel = HEALTH_PANEL,
		kind = "string",
		default = Addon.HealthFormats.BOTH,
		label = L.PREF_HEALTH_FORMAT,
		tooltip = L.PREF_HEALTH_FORMAT_TIP,
		choices = Addon.HealthFormats.Choices,
	},
	{
		key = Keys.HEALTH_VISIBILITY_MODE,
		panel = HEALTH_PANEL,
		kind = "string",
		default = Addon.VisibilityModes.ALWAYS,
		label = L.PREF_HEALTH_VISIBILITY,
		tooltip = L.PREF_HEALTH_VISIBILITY_TIP,
		choices = Addon.VisibilityModes.Choices,
	},
	{
		key = Keys.HEALTH_ANCHOR_POINT,
		panel = HEALTH_PANEL,
		kind = "string",
		default = "center",
		label = L.PREF_HEALTH_ANCHOR,
		tooltip = L.PREF_HEALTH_ANCHOR_TIP,
		choices = Addon.AnchorPoints.Choices,
	},
	{
		key = Keys.HEALTH_OFFSET_X,
		panel = HEALTH_PANEL,
		kind = "number",
		default = 0,
		label = L.PREF_OFFSET_X,
		tooltip = L.PREF_OFFSET_X_TIP,
		minimum = -200,
		maximum = 200,
		step = 1,
	},
	{
		key = Keys.HEALTH_OFFSET_Y,
		panel = HEALTH_PANEL,
		kind = "number",
		default = 0,
		label = L.PREF_OFFSET_Y,
		tooltip = L.PREF_OFFSET_Y_TIP,
		minimum = -200,
		maximum = 200,
		step = 1,
	},
	{
		key = Keys.HEALTH_FONT_SIZE,
		panel = HEALTH_PANEL,
		kind = "number",
		default = 10,
		label = L.PREF_FONT_SIZE,
		tooltip = L.PREF_HEALTH_FONT_SIZE_TIP,
		minimum = 8,
		maximum = 32,
		step = 1,
	},
	{
		key = Keys.NAME_ABOVE_BAR,
		panel = HEALTH_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_NAME_ABOVE_BAR,
		tooltip = L.PREF_NAME_ABOVE_BAR_TIP,
	},
	{
		key = Keys.NAME_BACKDROP,
		panel = HEALTH_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_NAME_BACKDROP,
		tooltip = L.PREF_NAME_BACKDROP_TIP,
	},
	{
		key = Keys.NAME_BACKDROP_COLOR,
		panel = HEALTH_PANEL,
		kind = "color",
		default = "000000",
		label = L.PREF_NAME_BACKDROP_COLOR,
		tooltip = L.PREF_NAME_BACKDROP_COLOR_TIP,
	},
	{
		key = Keys.NAME_BACKDROP_OPACITY,
		panel = HEALTH_PANEL,
		kind = "number",
		default = 20,
		label = L.PREF_NAME_BACKDROP_OPACITY,
		tooltip = L.PREF_NAME_BACKDROP_OPACITY_TIP,
		minimum = 0,
		maximum = 100,
		step = 5,
	},
	{
		key = Keys.NAME_BACKDROP_HEIGHT,
		panel = HEALTH_PANEL,
		kind = "number",
		default = 13,
		label = L.PREF_NAME_BACKDROP_HEIGHT,
		tooltip = L.PREF_NAME_BACKDROP_HEIGHT_TIP,
		minimum = 8,
		maximum = 28,
		step = 1,
	},
	{
		key = Keys.OWN_AURAS,
		panel = HEALTH_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_OWN_AURAS,
		tooltip = L.PREF_OWN_AURAS_TIP,
	},
	{
		key = Keys.AURA_FILTER,
		panel = HEALTH_PANEL,
		kind = "string",
		default = Addon.AuraFilters.OWN_DEBUFFS,
		label = L.PREF_AURA_FILTER,
		tooltip = L.PREF_AURA_FILTER_TIP,
		choices = Addon.AuraFilters.Choices,
	},
	{
		key = Keys.AURA_ICON_SIZE,
		panel = HEALTH_PANEL,
		kind = "number",
		default = 20,
		label = L.PREF_AURA_ICON_SIZE,
		tooltip = L.PREF_AURA_ICON_SIZE_TIP,
		minimum = 10,
		maximum = 44,
		step = 1,
	},
	{
		key = Keys.AURA_ICON_SPACING,
		panel = HEALTH_PANEL,
		kind = "number",
		default = 2,
		label = L.PREF_AURA_ICON_SPACING,
		tooltip = L.PREF_AURA_ICON_SPACING_TIP,
		minimum = 0,
		maximum = 12,
		step = 1,
	},
	{
		key = Keys.AURA_MAX_COUNT,
		panel = HEALTH_PANEL,
		kind = "number",
		default = 5,
		label = L.PREF_AURA_MAX_COUNT,
		tooltip = L.PREF_AURA_MAX_COUNT_TIP,
		minimum = 1,
		maximum = 12,
		step = 1,
	},
	{
		key = Keys.AURA_ANCHOR_POINT,
		panel = HEALTH_PANEL,
		kind = "string",
		default = "bottom",
		label = L.PREF_AURA_ANCHOR,
		tooltip = L.PREF_AURA_ANCHOR_TIP,
		choices = Addon.AnchorPoints.Choices,
	},
	{
		key = Keys.AURA_OFFSET_X,
		panel = HEALTH_PANEL,
		kind = "number",
		default = 0,
		label = L.PREF_AURA_OFFSET_X,
		tooltip = L.PREF_OFFSET_X_TIP,
		minimum = -200,
		maximum = 200,
		step = 1,
	},
	{
		key = Keys.AURA_OFFSET_Y,
		panel = HEALTH_PANEL,
		kind = "number",
		default = -4,
		label = L.PREF_AURA_OFFSET_Y,
		tooltip = L.PREF_OFFSET_Y_TIP,
		minimum = -200,
		maximum = 200,
		step = 1,
	},
	{
		key = Keys.PORTRAIT_ON_SELF,
		panel = HEALTH_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_PORTRAIT_SELF,
		tooltip = L.PREF_PORTRAIT_SELF_TIP,
	},
	{
		key = Keys.PORTRAIT_ON_FRIENDLY_PLAYERS,
		panel = HEALTH_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_PORTRAIT_FRIENDLY_PLAYERS,
		tooltip = L.PREF_PORTRAIT_FRIENDLY_PLAYERS_TIP,
	},
	{
		key = Keys.PORTRAIT_ON_ENEMY_PLAYERS,
		panel = HEALTH_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_PORTRAIT_ENEMY_PLAYERS,
		tooltip = L.PREF_PORTRAIT_ENEMY_PLAYERS_TIP,
	},
	{
		key = Keys.PORTRAIT_ON_FRIENDLY_NPCS,
		panel = HEALTH_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_PORTRAIT_FRIENDLY_NPCS,
		tooltip = L.PREF_PORTRAIT_FRIENDLY_NPCS_TIP,
	},
	{
		key = Keys.PORTRAIT_ON_ENEMY_NPCS,
		panel = HEALTH_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_PORTRAIT_ENEMY_NPCS,
		tooltip = L.PREF_PORTRAIT_ENEMY_NPCS_TIP,
	},
	{
		key = Keys.PORTRAIT_SIZE,
		panel = HEALTH_PANEL,
		kind = "number",
		default = 28,
		label = L.PREF_PORTRAIT_SIZE,
		tooltip = L.PREF_PORTRAIT_SIZE_TIP,
		minimum = 16,
		maximum = 48,
		step = 2,
	},
	{
		key = Keys.PORTRAIT_SIDE,
		panel = HEALTH_PANEL,
		kind = "string",
		default = "left",
		label = L.PREF_PORTRAIT_SIDE,
		tooltip = L.PREF_PORTRAIT_SIDE_TIP,
		choices = Addon.AnchorPoints.SideChoices,
	},
	{
		key = Keys.HEALTH_COLOR,
		panel = HEALTH_PANEL,
		kind = "color",
		default = "FFFFFF",
		label = L.PREF_HEALTH_COLOR,
		tooltip = L.PREF_HEALTH_COLOR_TIP,
	},

	{
		key = Keys.PLATES_FRIENDLY_PLAYERS,
		panel = PLATES_PANEL,
		kind = "boolean",
		-- O padrao do proprio jogo. Perfil novo nao passa pela semeadura, e um
		-- padrao nosso aqui e' escrito no cliente: ligado, encheria a tela de
		-- placas que ninguem pediu so' por criar um perfil.
		default = false,
		label = L.PREF_PLATES_FRIENDLY_PLAYERS,
		tooltip = L.PREF_PLATES_FRIENDLY_PLAYERS_TIP,
	},
	{
		key = Keys.PLATES_FRIENDLY_NPCS,
		panel = PLATES_PANEL,
		kind = "boolean",
		-- O padrao do proprio jogo, pela mesma razao da chave acima.
		default = false,
		label = L.PREF_PLATES_FRIENDLY_NPCS,
		tooltip = L.PREF_PLATES_FRIENDLY_NPCS_TIP,
	},
	{
		key = Keys.PLATES_FRIENDLY_PETS,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_PLATES_FRIENDLY_PETS,
		tooltip = L.PREF_PLATES_FRIENDLY_PETS_TIP,
	},
	{
		key = Keys.PLATES_FRIENDLY_TOTEMS,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_PLATES_FRIENDLY_TOTEMS,
		tooltip = L.PREF_PLATES_FRIENDLY_TOTEMS_TIP,
	},
	{
		key = Keys.PLATES_FRIENDLY_GUARDIANS,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_PLATES_FRIENDLY_GUARDIANS,
		tooltip = L.PREF_PLATES_FRIENDLY_GUARDIANS_TIP,
	},
	{
		key = Keys.PLATES_FRIENDLY_NAMES_ONLY,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_PLATES_FRIENDLY_NAMES_ONLY,
		tooltip = L.PREF_PLATES_FRIENDLY_NAMES_ONLY_TIP,
	},
	{
		key = Keys.PLATES_ENEMIES,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_PLATES_ENEMIES,
		tooltip = L.PREF_PLATES_ENEMIES_TIP,
	},
	{
		key = Keys.PLATES_ENEMY_MINIONS,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_PLATES_ENEMY_MINIONS,
		tooltip = L.PREF_PLATES_ENEMY_MINIONS_TIP,
	},
	{
		key = Keys.PLATES_ENEMY_MINUS,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_PLATES_ENEMY_MINUS,
		tooltip = L.PREF_PLATES_ENEMY_MINUS_TIP,
	},
	{
		key = Keys.PLATES_ENEMY_PETS,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_PLATES_ENEMY_PETS,
		tooltip = L.PREF_PLATES_ENEMY_PETS_TIP,
	},
	{
		key = Keys.PLATES_ENEMY_TOTEMS,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_PLATES_ENEMY_TOTEMS,
		tooltip = L.PREF_PLATES_ENEMY_TOTEMS_TIP,
	},
	{
		key = Keys.PLATES_ENEMY_GUARDIANS,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_PLATES_ENEMY_GUARDIANS,
		tooltip = L.PREF_PLATES_ENEMY_GUARDIANS_TIP,
	},
	{
		key = Keys.PLATES_ALWAYS,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_PLATES_ALWAYS,
		tooltip = L.PREF_PLATES_ALWAYS_TIP,
	},
	{
		key = Keys.PLATES_SELF,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_PLATES_SELF,
		tooltip = L.PREF_PLATES_SELF_TIP,
	},
	{
		key = Keys.HIDE_PLAYER_FRAME,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_HIDE_PLAYER_FRAME,
		tooltip = L.PREF_HIDE_PLAYER_FRAME_TIP,
	},
	{
		key = Keys.PLATES_STACKED,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_PLATES_STACKED,
		tooltip = L.PREF_PLATES_STACKED_TIP,
	},
	{
		key = Keys.HIDE_FRIENDLY_IN_COMBAT,
		panel = PLATES_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_HIDE_FRIENDLY_IN_COMBAT,
		tooltip = L.PREF_HIDE_FRIENDLY_IN_COMBAT_TIP,
	},
	{
		key = Keys.WINDOW_PLAYER,
		panel = WINDOWS_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_WINDOW_PLAYER,
		tooltip = L.PREF_WINDOW_PLAYER_TIP,
	},
	{
		key = Keys.WINDOW_TARGET,
		panel = WINDOWS_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_WINDOW_TARGET,
		tooltip = L.PREF_WINDOW_TARGET_TIP,
	},
	{
		key = Keys.WINDOW_FOCUS,
		panel = WINDOWS_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_WINDOW_FOCUS,
		tooltip = L.PREF_WINDOW_FOCUS_TIP,
	},
	{
		key = Keys.WINDOW_TOT,
		panel = WINDOWS_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_WINDOW_TOT,
		tooltip = L.PREF_WINDOW_TOT_TIP,
	},
	{
		key = Keys.WINDOW_HIDE_BLIZZARD,
		panel = WINDOWS_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_WINDOW_HIDE_BLIZZARD,
		tooltip = L.PREF_WINDOW_HIDE_BLIZZARD_TIP,
	},
	{
		key = Keys.WINDOW_PORTRAIT,
		panel = WINDOWS_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_WINDOW_PORTRAIT,
		tooltip = L.PREF_WINDOW_PORTRAIT_TIP,
	},
	{
		key = Keys.WINDOW_PLAYER_CLASS_COLOR,
		panel = WINDOWS_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_WINDOW_PLAYER,
		tooltip = L.PREF_WINDOW_CLASS_COLOR_TIP,
	},
	{
		key = Keys.WINDOW_PLAYER_COLOR,
		panel = WINDOWS_PANEL,
		kind = "color",
		default = "2EB335",
		label = L.PREF_WINDOW_HEALTH_COLOR,
		tooltip = L.PREF_WINDOW_HEALTH_COLOR_TIP,
	},
	{
		key = Keys.WINDOW_TARGET_CLASS_COLOR,
		panel = WINDOWS_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_WINDOW_TARGET,
		tooltip = L.PREF_WINDOW_CLASS_COLOR_TIP,
	},
	{
		key = Keys.WINDOW_TARGET_COLOR,
		panel = WINDOWS_PANEL,
		kind = "color",
		default = "2EB335",
		label = L.PREF_WINDOW_HEALTH_COLOR,
		tooltip = L.PREF_WINDOW_HEALTH_COLOR_TIP,
	},
	{
		key = Keys.WINDOW_FOCUS_CLASS_COLOR,
		panel = WINDOWS_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_WINDOW_FOCUS,
		tooltip = L.PREF_WINDOW_CLASS_COLOR_TIP,
	},
	{
		key = Keys.WINDOW_FOCUS_COLOR,
		panel = WINDOWS_PANEL,
		kind = "color",
		default = "2EB335",
		label = L.PREF_WINDOW_HEALTH_COLOR,
		tooltip = L.PREF_WINDOW_HEALTH_COLOR_TIP,
	},
	{
		key = Keys.WINDOW_TOT_CLASS_COLOR,
		panel = WINDOWS_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_WINDOW_TOT,
		tooltip = L.PREF_WINDOW_CLASS_COLOR_TIP,
	},
	{
		key = Keys.WINDOW_TOT_COLOR,
		panel = WINDOWS_PANEL,
		kind = "color",
		default = "2EB335",
		label = L.PREF_WINDOW_HEALTH_COLOR,
		tooltip = L.PREF_WINDOW_HEALTH_COLOR_TIP,
	},
}

Addon.PreferenceCatalog = PreferenceCatalog
